using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeatherForecastREST
{
    /*
* The classes RootObject, Data, Request, Time_Zone, Current_Condition, Weathericonurl, WeatherDesc
* were generated by copying JSON output from 'Rest Console' Chrome extension, 
* then in Visual Studio selecting EDIT > PASTE SPECIAL > Paste JSON as classes.
*/
    public class Current_Condition
    {
        public string observation_time { get; set; }
        public string temp_C { get; set; }
        public string temp_F { get; set; }
        public string weatherCode { get; set; }
        public Weathericonurl[] weatherIconUrl { get; set; }
        public Weatherdesc[] weatherDesc { get; set; }
        public string windspeedMiles { get; set; }
        public string windspeedKmph { get; set; }
        public string winddirDegree { get; set; }
        public string winddir16Point { get; set; }
        public string precipMM { get; set; }
        public string humidity { get; set; }
        public string visibility { get; set; }
        public string pressure { get; set; }
        public string cloudcover { get; set; }
        public string FeelsLikeC { get; set; }
        public string FeelsLikeF { get; set; }
    }
}