using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeatherForecastREST
{
    /*
* The classes RootObject, Data, Request, Time_Zone, Current_Condition, Weathericonurl, WeatherDesc
* were generated by copying JSON output from 'Rest Console' Chrome extension, 
* then in Visual Studio selecting EDIT > PASTE SPECIAL > Paste JSON as classes.
*/
    public class Data
    {
        public Request[] request { get; set; }
        public Time_Zone[] time_zone { get; set; }
        public Current_Condition[] current_condition { get; set; }
    }
}
